name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "README.md"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout target repository
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 17

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build
      run: |
        ./gradlew assembleRelease

    - name: Upload Aritfact
      uses: actions/upload-artifact@v4
      if: ${{  success() }}
      with:
        name: Debug Unsigned APK
        path: |
          app/build/outputs/apk/release/*.apk